### PR TITLE
Mac volume path incorrect

### PR DESCRIPTION
**Pull request by dhoer**
Mac installer would fail with the following message:
STDERR: rsync: link_stat "/Volumes/Mozilla Firefox/Mozilla Firefox.app" failed: No such file or directory

### CODE REVIEW

**Comment by dhoer** [comment]
Is it possible to get this merged since Mac installs are broken with the current version?

**Comment by tas50** [comment]
This looks good, but the vmware fusion stuff needs to come out.  I understand that is needed to test the Mac side, but it breaks everyone else's workflow.  Perhaps create a kitchen file with just the Mac testing suite.

**Comment by dhoer** [comment]
Makes sense.  I will comment it out for now.

**Comment by tas50** [comment]
The change needs to get rebased.  Also instead of commenting it out please create a 2nd kitchen.yml file for fusion.

**Comment by dhoer** [comment]
That is a great idea. I will add .kitchen.fusion.yml.

**Comment by dhoer** [comment]
Ok, I think I'm done making changes.  Let me know if you need anything else. Note that the changelog should be updated to reflect windows idempotency issue.

**Pull request merged**
